version: "3"

services:
  # Первый сервис — сервер
  server:
    build: server/
    command: python ./server.py
    ports:
      - "1234:1234"   # [порт_хоста]:[порт_внутри_контейнера]

  # Второй сервис — клиент
  client:
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server
